"""add timestamps column to lesson

Revision ID: 231c66cb4357
Revises: 85f4b4e1f072
Create Date: 2025-06-06 17:30:29.597849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '231c66cb4357'
down_revision = '85f4b4e1f072'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamps', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_column('timestamps')

    # ### end Alembic commands ###
