"""Add FSRS fields to VocabTerm

Revision ID: 2f7bc041c3da
Revises: 52b728bf53a0
Create Date: 2025-06-10 01:56:17.842374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f7bc041c3da'
down_revision = '52b728bf53a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vocab_term', schema=None) as batch_op:
        batch_op.add_column(sa.Column('difficulty', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('stability', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('reviews', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lapses', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vocab_term', schema=None) as batch_op:
        batch_op.drop_column('state')
        batch_op.drop_column('lapses')
        batch_op.drop_column('reviews')
        batch_op.drop_column('stability')
        batch_op.drop_column('difficulty')

    # ### end Alembic commands ###
