"""Add created_at to VocabTerm

Revision ID: 3a1d2449da97
Revises: 62f80b3c9369
Create Date: 2025-06-12 22:51:52.967104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a1d2449da97'
down_revision = '62f80b3c9369'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vocab_term', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vocab_term', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
