"""Add context_sentence to VocabTerm

Revision ID: 45434f2cd85e
Revises: b9bb99aa0341
Create Date: 2025-04-27 18:04:31.780373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45434f2cd85e'
down_revision = 'b9bb99aa0341'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vocab_term', schema=None) as batch_op:
        batch_op.add_column(sa.Column('context_sentence', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vocab_term', schema=None) as batch_op:
        batch_op.drop_column('context_sentence')

    # ### end Alembic commands ###
