"""add spacy model status to language

Revision ID: 52b728bf53a0
Revises: 5d5e707f1c83
Create Date: 2025-06-10 01:04:54.588789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52b728bf53a0'
down_revision = '5d5e707f1c83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('language', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spacy_model_status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('language', schema=None) as batch_op:
        batch_op.drop_column('spacy_model_status')

    # ### end Alembic commands ###
