"""add timestamp offset to lesson

Revision ID: 5d5e707f1c83
Revises: 78d9da663ef9
Create Date: 2025-06-10 00:03:45.220684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d5e707f1c83'
down_revision = '78d9da663ef9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp_offset', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_column('timestamp_offset')

    # ### end Alembic commands ###
