"""Add last_rating_type to VocabTerm

Revision ID: 70107648e11e
Revises: 2f7bc041c3da
Create Date: 2025-06-10 18:33:10.160489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70107648e11e'
down_revision = '2f7bc041c3da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vocab_term', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_rating_type', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vocab_term', schema=None) as batch_op:
        batch_op.drop_column('last_rating_type')

    # ### end Alembic commands ###
