"""Add grammar_summary to Lesson and Story models

Revision ID: 85f4b4e1f072
Revises: 99e23a1eee7c
Create Date: 2025-04-27 21:06:52.926277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85f4b4e1f072'
down_revision = '99e23a1eee7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grammar_summary', sa.Text(), nullable=True))

    with op.batch_alter_table('story', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audio_filename', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('grammar_summary', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story', schema=None) as batch_op:
        batch_op.drop_column('grammar_summary')
        batch_op.drop_column('audio_filename')

    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_column('grammar_summary')

    # ### end Alembic commands ###
