"""Add readability_score to Lesson and Story

Revision ID: 8a207a18ab21
Revises: f2d2d38ffefe
Create Date: 2025-06-13 02:08:02.805014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a207a18ab21'
down_revision = 'f2d2d38ffefe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('readability_score', sa.Float(), nullable=False))

    with op.batch_alter_table('story', schema=None) as batch_op:
        batch_op.add_column(sa.Column('readability_score', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story', schema=None) as batch_op:
        batch_op.drop_column('readability_score')

    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_column('readability_score')

    # ### end Alembic commands ###
