"""Add cover_image_filename to Story

Revision ID: 99e23a1eee7c
Revises: c52c12f7c353
Create Date: 2025-04-27 19:39:43.197814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99e23a1eee7c'
down_revision = 'c52c12f7c353'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_image_filename', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story', schema=None) as batch_op:
        batch_op.drop_column('cover_image_filename')

    # ### end Alembic commands ###
