"""Initial migration with SRS fields

Revision ID: b9bb99aa0341
Revises: 
Create Date: 2025-04-27 17:17:12.232285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9bb99aa0341'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dictionary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('url_pattern', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('language',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=True),
    sa.Column('days_learning', sa.Integer(), nullable=True),
    sa.Column('card_background_image', sa.String(length=200), nullable=True),
    sa.Column('active_dictionary_ids', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('setting',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('lesson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('image_filename', sa.String(length=200), nullable=True),
    sa.Column('media_url', sa.String(length=500), nullable=True),
    sa.Column('youtube_url', sa.String(length=500), nullable=True),
    sa.Column('audio_filename', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vocab_term',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(length=200), nullable=False),
    sa.Column('lemma', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('translation', sa.Text(), nullable=True),
    sa.Column('next_review_date', sa.DateTime(), nullable=True),
    sa.Column('interval', sa.Integer(), nullable=True),
    sa.Column('ease_factor', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('language_id', 'lemma', name='uq_language_lemma'),
    sa.UniqueConstraint('language_id', 'term', name='uq_language_term')
    )
    with op.batch_alter_table('vocab_term', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vocab_term_lemma'), ['lemma'], unique=False)
        batch_op.create_index(batch_op.f('ix_vocab_term_next_review_date'), ['next_review_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_vocab_term_term'), ['term'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vocab_term', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vocab_term_term'))
        batch_op.drop_index(batch_op.f('ix_vocab_term_next_review_date'))
        batch_op.drop_index(batch_op.f('ix_vocab_term_lemma'))

    op.drop_table('vocab_term')
    op.drop_table('lesson')
    op.drop_table('setting')
    op.drop_table('language')
    op.drop_table('dictionary')
    # ### end Alembic commands ###
