"""Manually add readability_score to Lesson and Story models

Revision ID: c2a40a0a4e5a
Revises: f2d2d38ffefe
Create Date: 2024-07-31 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2a40a0a4e5a'
down_revision = 'f2d2d38ffefe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson', sa.Column('readability_score', sa.Float(), nullable=True, server_default='0.0'))
    op.add_column('story', sa.Column('readability_score', sa.Float(), nullable=True, server_default='0.0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('story', 'readability_score')
    op.drop_column('lesson', 'readability_score')
    # ### end Alembic commands ###
