"""Add indexes to VocabTerm

Revision ID: f2d2d38ffefe
Revises: 3a1d2449da97
Create Date: 2025-06-13 00:55:30.139015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2d2d38ffefe'
down_revision = '3a1d2449da97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vocab_term', schema=None) as batch_op:
        batch_op.create_index('ix_vocab_term_language_status', ['language_id', 'status'], unique=False)
        batch_op.create_index('ix_vocab_term_next_review', ['next_review_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vocab_term', schema=None) as batch_op:
        batch_op.drop_index('ix_vocab_term_next_review')
        batch_op.drop_index('ix_vocab_term_language_status')

    # ### end Alembic commands ###
