"""Add SRSSettings model

Revision ID: fa90e95237ee
Revises: 45434f2cd85e
Create Date: 2025-04-27 18:35:07.910216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa90e95237ee'
down_revision = '45434f2cd85e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('srs_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('new_cards_per_day', sa.Integer(), nullable=False),
    sa.Column('max_reviews_per_day', sa.Integer(), nullable=False),
    sa.Column('learning_steps', sa.String(length=100), nullable=False),
    sa.Column('graduating_interval', sa.Integer(), nullable=False),
    sa.Column('easy_interval', sa.Integer(), nullable=False),
    sa.Column('starting_ease', sa.Float(), nullable=False),
    sa.Column('easy_bonus', sa.Float(), nullable=False),
    sa.Column('interval_modifier', sa.Float(), nullable=False),
    sa.Column('hard_interval_multiplier', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('language_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('srs_settings')
    # ### end Alembic commands ###
